swagger: "2.0"
info:
  description: "API de videogameecommerce"
  version: "1.0.0"
  title: "Videogame Ecommerce"
  termsOfService: "http://videogameecommerce.herokuapp.com/terms/"
  contact:
    email: "lalo0892@gmial.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "videogameecommerce.herokuapp.com"
basePath: "/api"
tags:
- name: "product"
  description: "Products en la store"
  externalDocs:
    description: "Find out more"
    url: "http://videogameecommerce.herokuapp.com/docs"
schemes:
- "https"
- "http"
paths:
  /products:
    post:
      tags:
      - "product"
      summary: "Add a new videogame to the store"
      description: ""
      operationId: "addProduct"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Product object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        "404":
          description: "Product not found"
        "500":
          description: "Internal Server error"
  /products/{productId}:
    get:
      tags:
      - "product"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProductById"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of product to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Product"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
    put:
      tags:
      - "product"
      summary: "Updates a product in the store with json body"
      description: ""
      operationId: "updateProduct"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Product object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        "500":
          description: "Internal server error"
        "404":
          description: "Product not found"
    delete:
      tags:
      - "product"
      summary: "Deletes a product"
      description: ""
      operationId: "deleteProduct"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "Product id to delete"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Product not found"
definitions:
  Product:
    type: "object"
    required:
    - "name"
    - "platform"
    - "price"
    - "description"
    properties:
      id:
        type: "string"
        example: "6276b1cdb7131671a55cd611"
      name:
        type: "string"
        example: "Ghost of Tsushima"
      price:
        type: "integer"
        format: "int64"
        example: "1340"
      platform:
        type: "string"
        description: "platform that the game is available"
        enum:
        - "PS4"
        - "Xbox"
        - "Nintendo"