GET http://localhost:8080/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNzY5MjlhOWE3NzczMDNjZTQxNTU2ZCIsImZpcnN0bmFtZSI6IkxhbG8iLCJsYXN0bmFtZSI6IlZlbGF6cXVleiIsImVtYWlsIjoibGFsbzA4OTJAZ21haWwuY29tIiwicGhvbmUiOiIrNTI0NDIxOTc3MzU1IiwiaWF0IjoxNjU0MjY2NjI1LCJleHAiOjE2NTQyNjY4MDV9.DSioxBVv5at-2QRkokJZ1ZjjUtifhFsZ7UrVXDwwdb0